"""
Section 9 deliverable: export the current schema as PostgreSQL DDL,
plus a markdown-table ER overview (no diagram images -- tables only,
per project preference).

Generated by introspecting the real SQLAlchemy models built across
Sections 4-8 (Trace/TraceEvent, MetricPoint, Evaluation, Regression,
RCAReport) -- not hand-maintained, so it can never silently drift out
of sync with the tables actually in use.

Note: DDL is compiled against the PostgreSQL dialect (matching the
master plan's "PostgreSQL Schema" naming) even though this project has
only been runtime-tested against SQLite in this sandbox -- see
sentinel/trace/db.py for why. Compiling against a dialect doesn't
require an actual Postgres connection, just the dialect definition.

Run:
    python -m sentinel.export_schema
"""

import os

from sqlalchemy.schema import CreateTable
from sqlalchemy.dialects import postgresql

from .trace.models import Base
# Import every models module so its tables register on Base.metadata
# before we introspect it -- SQLAlchemy only knows about a table once
# its module has been imported at least once.
from .trace import models as _trace_models  # noqa: F401
from .metrics import models as _metrics_models  # noqa: F401
from .evaluation import models as _evaluation_models  # noqa: F401
from .regression import models as _regression_models  # noqa: F401
from .rca import models as _rca_models  # noqa: F401
from .alerting import models as _alerting_models  # noqa: F401


def export_schema_sql(path: str = "docs/schema.sql") -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("-- Auto-generated from SQLAlchemy models -- do not hand-edit.\n")
        f.write("-- Regenerate with: python -m sentinel.export_schema\n")
        f.write("-- Compiled for PostgreSQL; this project runs on SQLite locally (see trace/db.py).\n\n")
        for table in Base.metadata.sorted_tables:
            ddl = str(CreateTable(table).compile(dialect=postgresql.dialect())).strip()
            f.write(ddl + ";\n\n")
    print(f"Wrote schema to {path}")


def export_er_overview_md(path: str = "docs/er_overview.md") -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    lines = ["# Sentinel AI — Schema Overview (auto-generated)\n",
             "Regenerate with `python -m sentinel.export_schema`. Do not hand-edit.\n"]

    for table in Base.metadata.sorted_tables:
        lines.append(f"## `{table.name}`\n")
        lines.append("| Column | Type | PK | FK | Nullable |")
        lines.append("|---|---|---|---|---|")
        for col in table.columns:
            fk = ", ".join(str(fk.target_fullname) for fk in col.foreign_keys) or ""
            pk = "✓" if col.primary_key else ""
            nullable = "" if col.nullable else "NOT NULL"
            lines.append(f"| {col.name} | {col.type} | {pk} | {fk} | {nullable} |")
        lines.append("")

    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote ER overview to {path}")


if __name__ == "__main__":
    export_schema_sql()
    export_er_overview_md()
